config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  macbook:
    dotfiles:
    - f_alacritty.yml
    - f_zshrc
