actions:
  sfmono: brew tap epk/epk && brew cask install font-sf-mono-nerd-font
config:
  backup: false
  banner: true
  create: true
  dotpath: ~/Projects/dotfiles/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_alacritty.yml:
    actions:
      - sfmono
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  macbook:
    dotfiles:
    - f_alacritty.yml
    - f_zshrc
  sam:
    dotfiles:
    - f_zshrc
  macbook_nike:
    dotfiles:
    - f_alacritty.yml
    - f_zshrc
