actions:
  sfmono: brew tap epk/epk && brew cask install font-sf-mono-nerd-font
  fzf-tab: rm -rf ~/Projects/fzf-tab && git clone https://github.com/Aloxaf/fzf-tab ~/Projects/fzf-tab
  autosuggestions: rm -rf ~/.zsh/zsh-autosuggestions && git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
  zsh-syntax: rm -rf ~/.zsh/zsh-syntax-highlighting && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting 
config:
  backup: false
  banner: true
  create: true
  dotpath: ~/Projects/dotfiles/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_alacritty.yml:
    actions:
    - sfmono
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_zshrc:
    actions:
    - fzf-tab
    - autosuggestions
    - zsh-syntax
    src: zshrc
    dst: ~/.zshrc
  f_config.yaml:
    src: config/dotdrop/config.yaml
    dst: ~/.config/dotdrop/config.yaml
profiles:
  macbook:
    dotfiles:
    - f_alacritty.yml
    - f_zshrc
    - f_config.yaml
  sam:
    dotfiles:
    - f_zshrc
    - f_config.yaml
  macbook_nike:
    dotfiles:
    - f_alacritty.yml
    - f_zshrc
    - f_config.yaml
