dynvariables:
  os: uname -s | tr '[:upper:]' '[:lower:]'
actions:
  install-tpm: rm -rf ~/.tmux/plugins &&  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  install-tmux-plugins: ~/.tmux/plugins/tpm/scripts/install_plugins.sh
  sfmono: brew tap epk/epk && brew cask install font-sf-mono-nerd-font
  fzf-tab: rm -rf ~/Projects/fzf-tab && git clone https://github.com/Aloxaf/fzf-tab
    ~/Projects/fzf-tab
  autosuggestions: rm -rf ~/.zsh/zsh-autosuggestions && git clone https://github.com/zsh-users/zsh-autosuggestions
    ~/.zsh/zsh-autosuggestions
  zsh-syntax: rm -rf ~/.zsh/zsh-syntax-highlighting && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
    ~/.zsh/zsh-syntax-highlighting
  plug: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
config:
  backup: false
  banner: true
  create: true
  dotpath: ~/Projects/dotfiles/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_alacritty.yml:
    actions:
    - sfmono
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_zshrc:
    actions:
    - fzf-tab
    - autosuggestions
    - zsh-syntax
    src: zshrc
    dst: ~/.zshrc
  f_config.yaml:
    src: config/dotdrop/config.yaml
    dst: ~/.config/dotdrop/config.yaml
  f_config:
    src: ncmpcpp/config
    dst: ~/.ncmpcpp/config
  f_init.vim:
    actions:
    - plug
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_tmux.conf:
    actions:
    - install-tpm
    - install-tmux-plugins
    src: tmux.conf
    dst: ~/.tmux.conf
  f_nord-status-content.conf:
    src: tmux/plugins/nord-tmux/src/nord-status-content.conf
    dst: ~/.tmux/plugins/nord-tmux/src/nord-status-content.conf
profiles:
  macbook:
    dotfiles:
    - f_alacritty.yml
    - f_zshrc
    - f_config.yaml
    - f_config
    - f_init.vim
    - f_tmux.conf
    - f_nord-status-content.conf
  sam:
    dotfiles:
    - f_zshrc
    - f_config.yaml
    - f_init.vim
    - f_tmux.conf
  macbook_nike:
    dotfiles:
    - f_alacritty.yml
    - f_zshrc
    - f_config
    - f_config.yaml
    - f_tmux.conf
    - f_nord-status-content.conf
    - f_init.vim
    - f_nord-status-content.conf
