dynvariables:
  os: uname -s | tr '[:upper:]' '[:lower:]'
actions:
  install-tpm: rm -rf ~/.tmux/plugins &&  git clone https://github.com/tmux-plugins/tpm
    ~/.tmux/plugins/tpm
  install-tmux-plugins: ~/.tmux/plugins/tpm/tpm && ~/.tmux/plugins/tpm/scripts/install_plugins.sh
  sfmono: brew tap epk/epk && brew cask install font-sf-mono-nerd-font
  fzf-tab: rm -rf ~/Projects/fzf-tab && git clone https://github.com/Aloxaf/fzf-tab
    ~/Projects/fzf-tab
  autosuggestions: rm -rf ~/.zsh/zsh-autosuggestions && git clone https://github.com/zsh-users/zsh-autosuggestions
    ~/.zsh/zsh-autosuggestions
  zsh-syntax: rm -rf ~/.zsh/zsh-syntax-highlighting && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
    ~/.zsh/zsh-syntax-highlighting
  plug: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
config:
  backup: false
  banner: true
  create: true
  dotpath: ~/Projects/dotfiles/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  alacritty:
    actions:
    - sfmono
    src: alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  zsh:
    actions:
    - fzf-tab
    - autosuggestions
    - zsh-syntax
    src: zsh/zshrc
    dst: ~/.zshrc
  dotdrop:
    src: dotdrop/config.yaml
    dst: ~/.config/dotdrop/config.yaml
  ncmpcpp:
    src: ncmpcpp/config
    dst: ~/.ncmpcpp/config
  neovim:
    actions:
    - plug
    src: nvim/init.vim
    dst: ~/.config/nvim/init.vim
  tmux:
    src: tmux/tmux.conf
    dst: ~/.tmux.conf
    actions:
    - install-tpm
    - install-tmux-plugins
  f_nord-status-content.conf:
    src: tmux/plugins/nord-tmux/src/nord-status-content.conf
    dst: ~/.tmux/plugins/nord-tmux/src/nord-status-content.conf
  f_current_song.sh:
    src: Projects/current_song.sh
    dst: ~/Projects/current_song.sh
profiles:
  macbook:
    dotfiles:
    - alacritty
    - zsh
    - dotdrop
    - ncmpcpp
    - neovim
    - tmux
  sam:
    dotfiles:
    - zsh
    - dotdrop
    - neovim
    - tmux
  macbook_nike:
    dotfiles:
    - alacritty
    - zsh
    - ncmpcpp
    - dotdrop
    - tmux
    - neovim
